version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: echo "Install node"
      - node/install:
          install-yarn: true
          node-version: '15.9.0'
      - run: node --version
      - run: echo "Install Package"
      - run: yarn
      - run: echo "Linting"
      - run: yarn lint
      - run: echo "Execute Migration"
      - run: yarn migration
      - run: echo "Install Package"
      - run: yarn start

workflows:
  deploy-workflow:
    jobs:
      - deploy
